name: Build Release
on:
  deployment: {}
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20.x]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: actions/checkout@v4
        name: Checkout Flexget
        with:
          ref: develop
          repository: Flexget/flexget
          path: flexget
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Git
        run: |
          git config --global user.email $GIT_EMAIL
          git config --global user.name $GIT_USERNAME
          git fetch --no-tag origin +refs/heads/master:refs/remotes/origin/master
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ matrix.node }}-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ matrix.node }}-deps-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Set Deployment Status Pending
        uses: ./.github/actions/deployment-status
        with:
          status: pending
          token: ${{ github.token }}
      - name: Run Build
        run: VERSION=$(yarn -s release:bump release --dry-run) yarn build
      - name: Zip Dist Folder
        run: zip -r /tmp/dist.zip ./dist
      - name: Release
        run: scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Deployment Status Success
        uses: ./.github/actions/deployment-status
        with:
          status: success
          token: ${{ github.token }}
      - name: Set Deployment Status Failure
        if: failure() || cancelled()
        uses: ./.github/actions/deployment-status
        with:
          status: failure
          token: ${{ github.token }}
